/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/formatTime`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/parts/CustomModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/route/EditRouteModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/creatingARoute` | `/creatingARoute`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/savingARoute` | `/savingARoute`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/routes/[id]` | `/routes/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/routes/weather/[id]` | `/routes/weather/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/formatTime`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/parts/CustomModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/route/EditRouteModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/creatingARoute` | `/creatingARoute`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/savingARoute` | `/savingARoute`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/routes/[id]` | `/routes/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(main)'}/routes/weather/[id]` | `/routes/weather/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/loading${`?${string}` | `#${string}` | ''}` | `/../utils/formatTime${`?${string}` | `#${string}` | ''}` | `/../components/ui/parts/CustomModal${`?${string}` | `#${string}` | ''}` | `/../components/route/EditRouteModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/creatingARoute${`?${string}` | `#${string}` | ''}` | `/creatingARoute${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/savingARoute${`?${string}` | `#${string}` | ''}` | `/savingARoute${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(tabs)'}/weather${`?${string}` | `#${string}` | ''}` | `/weather${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/formatTime`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/parts/CustomModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/route/EditRouteModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/creatingARoute` | `/creatingARoute`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/savingARoute` | `/savingARoute`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownInputParams; } | `${'/(main)'}/routes/${Router.SingleRoutePart<T>}` | `/routes/${Router.SingleRoutePart<T>}` | `${'/(main)'}/routes/weather/${Router.SingleRoutePart<T>}` | `/routes/weather/${Router.SingleRoutePart<T>}` | { pathname: `${'/(main)'}/routes/[id]` | `/routes/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/routes/weather/[id]` | `/routes/weather/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
